version: '3.1'

services:
  frontend:
    build:
      context: ./neural-roots-ui
    volumes:
      - react_build:/neural-roots-app/neural-roots-ui/build
      
  nginx:
    image: nginx:latest
    ports:
      - 80:8001
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/neuralroots.in/
    depends_on:
      - frontend
volumes:
  react_build: